name: Azure Static Web App CI/CD - Frontend

on:
  push:
    branches:
      - main
    paths:
      # Gatilho: Aciona o deploy do frontend quando houver alterações em arquivos React/Node
      - 'src/**'
      - 'public/**' # Inclui o index.html
      - 'package.json' 
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: 1. Instalar NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 2. Instalar Dependências do Frontend
        run: npm install

      - name: 3. Build da Aplicação React
        run: npm run build 
        
      - name: 4. Deploy para Azure Static Web App
        id: builddeploy
        uses: azure/static-web-apps-deploy@v1
        with:
          # CRÍTICO: SUBSTITUA PELO NOME EXATO DO SEU SEGREDO NO GITHUB!
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_WAVE_069413D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/" 
          output_location: "build"